version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: shemonstervintage-db   # optional, mainly for `docker ps`
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shemonstervintage
      MYSQL_USER: wishlist_user
      MYSQL_PASSWORD: wishlist_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d:ro

  php:
    build: ./ 
    container_name: shemonstervintage-php
    working_dir: /var/www
    volumes:
      - ../../..:/var/www 
    command: php -S 0.0.0.0:8000 -t /var/www/api /var/www/api/server.php
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db                     # ✅ Use service name, not container_name
      DB_PORT: 3306
      DB_NAME: shemonstervintage
      DB_USER: wishlist_user
      DB_PASS: wishlist_pass

volumes:
  db_data:
